jobs:
  test:
    uses: ./.github/workflows/feature.yaml
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: setup repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
name: Test, build and release
on:
  push:
    branches:
      - main
